set(EXAMPLE_SOURCES_PATH       ${PROJECT_SOURCES}/${EXAMPLE_NAME})

include_directories(${EXAMPLE_SOURCES_PATH})

file(GLOB EXAMPLE_SOURCES
        "${EXAMPLE_SOURCES_PATH}/*.cpp"
)
message(${EXAMPLE_SOURCES})

add_executable(${EXAMPLE_NAME} ${EXAMPLE_SOURCES})
set_target_properties(${EXAMPLE_NAME} PROPERTIES LINKER_LANGUAGE CXX)
target_compile_options(${EXAMPLE_NAME} PRIVATE -Wno-long-long -Wno-varargs -Wall -Werror)

# Define installation folders
install(TARGETS ${EXAMPLE_NAME} 
        RUNTIME DESTINATION ${PROJECT_BINARIES}/${EXAMPLE_NAME}
        LIBRARY DESTINATION ${PROJECT_BINARIES}/${EXAMPLE_NAME}
        ARCHIVE DESTINATION ${PROJECT_LIBS}/${EXAMPLE_NAME})
